name: "🐞 Bug report"
description: Report a bug to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) Go to..., 2) Click..., 3) See error"
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "OS, Browser/Node version, commit SHA"
  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      render: shell
