export const SETUP_STUDY_SESSION_OPTIONS: string[] = [
	'Mathematics',
	'Biology',
	'Chemistry',
	'Physics',
	'Agriculture',
	'Computer Science',
	'Psychology',
	'Environmental Sciences',
	'Geology',
	'Geography',
	'Kinesiology',
	'Business',
	'History',
	'Anthropology',
	'Language Studies',
	'Social Work',
	'Communications',
];
