//Test funcion was generated by ChatGpt
import { act, fireEvent, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { render } from '~/utilities/testing';
import { FriendsHeader } from './FriendsHeader';

vi.mock('react-router-dom', async () => {
  const actual =
    await vi.importActual<typeof import('react-router-dom')>(
      'react-router-dom',
    );

  const useLoaderData = vi.fn();
  const useSubmit = vi.fn(() => vi.fn());
  const useNavigate = vi.fn(() => vi.fn());

  const Form = ({
    onSubmit,
    children,
    method,
  }: {
    onSubmit: React.FormEventHandler<HTMLFormElement>;
    children: React.ReactNode;
    method: string;
  }) => (
    <form method={method} onSubmit={onSubmit}>
      {children}
    </form>
  );

  return Object.assign({}, actual, {
    __mocks: { useLoaderData, useNavigate, useSubmit },
    Form,
    useLoaderData,
    useNavigate,
    useSubmit,
  });
});

import * as Router from 'react-router-dom';

describe('FriendsHeader', () => {
  const mocks = (
    Router as unknown as {
      __mocks: {
        useLoaderData: ReturnType<typeof vi.fn>;
        useSubmit: ReturnType<typeof vi.fn>;
        useNavigate: ReturnType<typeof vi.fn>;
      };
    }
  ).__mocks;

  const { useLoaderData, useSubmit, useNavigate } = mocks;

  const mockLoaderData = {
    data: {
      friendCount: { data: { count: 5 } },
      requestCount: { data: { count: 2 } },
    },
  };

  beforeEach(() => {
    vi.useFakeTimers();
    useLoaderData.mockReturnValue(mockLoaderData);
    useSubmit.mockReturnValue(vi.fn());
    useNavigate.mockReturnValue(vi.fn());
    localStorage.clear();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('renders search input', () => {
    render(
      <MemoryRouter>
        <FriendsHeader isHidden />
      </MemoryRouter>,
    );
    expect(
      screen.getByPlaceholderText('Search friends...'),
    ).toBeInTheDocument();
  });

  it('allows typing in search field', () => {
    render(
      <MemoryRouter>
        <FriendsHeader isHidden />
      </MemoryRouter>,
    );
    const input = screen.getByPlaceholderText('Search friends...');
    fireEvent.change(input, { target: { value: 'john' } });
    expect((input as HTMLInputElement).value).toBe('john');
  });

  it('calls submit() after debounce delay', async () => {
    const submitSpy = vi.fn();
    useSubmit.mockReturnValue(submitSpy);

    render(
      <MemoryRouter>
        <FriendsHeader isHidden />
      </MemoryRouter>,
    );

    const input = screen.getByPlaceholderText('Search friends...');
    fireEvent.change(input, { target: { value: 'alex' } });

    await act(async () => {
      vi.advanceTimersByTime(700);
    });

    expect(submitSpy).toHaveBeenCalled();
  });

  it('renders stats cards correctly', () => {
    render(
      <MemoryRouter>
        <FriendsHeader isHidden />
      </MemoryRouter>,
    );
    expect(screen.getByTestId('friends-card')).toBeInTheDocument();
    expect(screen.getByTestId('requests-card')).toBeInTheDocument();
    expect(screen.getByTestId('online-card')).toBeInTheDocument();
    expect(screen.getByTestId('studying-card')).toBeInTheDocument();
  });

  it('renders back button when isHidden = false', () => {
    render(
      <MemoryRouter>
        <FriendsHeader isHidden={false} />
      </MemoryRouter>,
    );
    expect(screen.getByRole('button')).toBeInTheDocument();
  });

  it('clears searchTerm and navigates when back button is clicked', () => {
    const navigateSpy = vi.fn();
    useNavigate.mockReturnValue(navigateSpy);
    localStorage.setItem('searchTerm', 'hello');

    render(
      <MemoryRouter>
        <FriendsHeader isHidden={false} />
      </MemoryRouter>,
    );

    fireEvent.click(screen.getByRole('button'));
    expect(localStorage.getItem('searchTerm')).toBeNull();
    expect(navigateSpy).toHaveBeenCalled();
  });
});
