import {
  ActionIcon,
  Box,
  Card,
  Center,
  Flex,
  Input,
  SimpleGrid,
  Text,
  TextInput,
} from '@mantine/core';
import {
  IconArrowLeft,
  IconCircleFilled,
  IconSearch,
  IconUserPlus,
  IconUsers,
} from '@tabler/icons-react';
import { useEffect, useRef, useState } from 'react';
import { Form, useLoaderData, useNavigate, useSubmit } from 'react-router-dom';
import {
  FRIENDS,
  FRIENDS_CARD_ONLINE,
  FRIENDS_CARD_STUDYING,
  FRIENDS_HEADER_DESCRIPTION,
  FRIENDS_SEARCHBAR_PLACEHOLDER,
  FRIENDS_TAB_FRIENDS,
  FRIENDS_TAB_REQUESTS,
} from '~/constants';

type props = {
  isHidden: boolean;
};

export const FriendsHeader = ({ isHidden }: props) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [inputValue, setInputValue] = useState(searchTerm);
  const formRef = useRef<HTMLFormElement>(null);
  const submit = useSubmit();
  const navigate = useNavigate();

  //The timeout logic was generated by google AI
  useEffect(() => {
    // Set a timeout to update the searchTerm state after 500ms of inactivity
    const timeoutId = setTimeout(() => {
      setSearchTerm(inputValue);
    }, 700);

    // Clean up the previous timeout if the inputValue changes again
    return () => {
      clearTimeout(timeoutId);
    };
  }, [inputValue]); // The effect runs every time inputValue changes

  useEffect(() => {
    if (searchTerm) {
      localStorage.setItem('searchTerm', searchTerm);
      submit(formRef.current);
    }
  }, [searchTerm, submit]);

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(event.target.value);
  };

  const loaderdata = useLoaderData();
  const friendCount = loaderdata.data.friendCount.data.count;
  const requestCount = loaderdata.data.requestCount.data.count;

  const stats = [
    {
      icon: <IconUsers color='blue' size={28} />,
      label: FRIENDS_TAB_FRIENDS,
      value: friendCount,
    },
    {
      icon: <IconUserPlus color='#40c057' size={28} />,
      label: FRIENDS_TAB_REQUESTS,
      value: requestCount,
    },
    {
      icon: <IconCircleFilled color='#40c057' size={28} />,
      label: FRIENDS_CARD_ONLINE,
      value: '2',
    },
    {
      icon: <IconCircleFilled color='blue' size={28} />,
      label: FRIENDS_CARD_STUDYING,
      value: '1',
    },
  ];
  const prevSearch = localStorage.getItem('searchTerm');

  return (
    <Box>
      <Flex direction='column' gap='md' p='lg' w='30%'>
        <Text data-testid='Friends header' fw={700} fz='h1'>
          {FRIENDS_TAB_FRIENDS}
        </Text>
        <Text c='dimmed'>{FRIENDS_HEADER_DESCRIPTION}</Text>
        <Form method='post' ref={formRef}>
          <Input name='formtype' type='hidden' value='searchFriend' />
          <Flex direction='row' gap='sm'>
            {!isHidden && (
              <ActionIcon
                color='black'
                onClick={() => {
                  localStorage.removeItem('searchTerm');
                  navigate(FRIENDS);
                }}
                variant='outline'
              >
                <IconArrowLeft />
              </ActionIcon>
            )}
            <TextInput
              defaultValue={prevSearch ? prevSearch : ''}
              leftSection={<IconSearch />}
              name='searchUser'
              onChange={(e) => handleInputChange(e)}
              placeholder={FRIENDS_SEARCHBAR_PLACEHOLDER}
              variant='filled'
            />
          </Flex>
        </Form>
      </Flex>

      <Flex direction='row' gap='md' p='lg'>
        <SimpleGrid cols={{ base: 2, sm: 4 }} spacing='lg' w='100%'>
          {stats.map((item) => (
            <Card
              data-testid={`${item.label
                .toLowerCase()
                .replace(/\s+/g, '-')}-card`}
              key={item.label}
              p='lg'
              radius='md'
              shadow='sm'
              style={{ borderRadius: '12px' }}
              withBorder
            >
              <Center style={{ flexDirection: 'column', gap: '6px' }}>
                {item.icon}
                <Text fw={700} fz='xl'>
                  {item.value}
                </Text>
                <Text c='dimmed' fz='sm'>
                  {item.label}
                </Text>
              </Center>
            </Card>
          ))}
        </SimpleGrid>
      </Flex>
    </Box>
  );
};
