export * from './Study'
export * from './Login'
export * from './ForgotPassword'
export * from './SignUp'
export * from './Home'
export * from './Badges'
export * from './UserProfile'
export * from './UpdatePassword'