export * from './Badges';
export * from './ForgotPassword';
export * from './Home';
export * from './login';
export * from './signup';
export * from './Study';
export * from './UpdatePassword';
export * from './UserProfile';
export * from './logout';
