import {
  Anchor,
  Button,
  Checkbox,
  Container,
  Group,
  Paper,
  PasswordInput,
  Text,
  TextInput,
  Title,
} from "@mantine/core";
import { useNavigate } from "react-router-dom";
import { useRef } from "react";
import { validateEmail } from "~/utilities/testing/emailValidation";
import { equalPasswords } from "~/utilities/testing/passwordValidation";
import { notifications } from "@mantine/notifications";
import { useState } from "react";
import { Box } from "@mantine/core";

export function SignUpForm() {
  const navigate = useNavigate();
  const password_1 = useRef<HTMLInputElement>(null);
  const password_2 = useRef<HTMLInputElement>(null);
  const email = useRef<HTMLInputElement>(null);

  //The logic for updating the color state of the password requirement text was generated by chatGPT
  const [password, setPassword] = useState("");
  const passwordLen = 8;
  const checkRules = (value: string) => ({
    matchesLen: value.length > passwordLen,
    hasLowercase: /[a-z]/.test(value),
    hasUppercase: /[A-Z]/.test(value),
    hasDigit: /\d/.test(value),
    hasSpecial: /[@#$%^&*()\-_+=]/.test(value),
  });
  const rules = checkRules(password);

  const handleClick = () => {
    if (password_1.current && password_2.current && email.current) {
      if (
        validateEmail(email.current.value) &&
        equalPasswords(password_1.current.value, password_2.current.value)
      ) {
        notifications.show({
          title: "Account Created Successfully",
          message: "Begin Your Gamified Learning experience now",
          color: "green",
        });
        navigate("/study");
      }
    }
  };

  return (
    <Box
      style={{
        backgroundColor: "#f0f0f0",
        padding: "20px",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        minHeight: "center",
        margin: "0",
      }}
    >
      <Container size={420} my={40} className="classes.container">
        <Paper withBorder shadow="xl" p={22} mt={30} radius="lg">
          <Text c={rules.matchesLen ? "green" : "red"}>
            • Password must be at least one 8 characters long
          </Text>
          <Text c={rules.hasLowercase ? "green" : "red"}>
            • Password must contain at least one lowercase letter
          </Text>
          <Text c={rules.hasUppercase ? "green" : "red"}>
            • Password must contain at least one uppercase letter
          </Text>
          <Text c={rules.hasDigit ? "green" : "red"}>
            • Password must contain at least one digit (0-9)
          </Text>
          <Text c={rules.hasSpecial ? "green" : "red"}>
            • Password must contain at least one special character (@, #, $, %,
            ^, &, *, (, ), -, _, +, =)
          </Text>
        </Paper>
        <Paper withBorder shadow="sm" p={22} mt={30} radius="md">
          <Title ta="center" ff="Inter, sans-serif">
            Join Studly
          </Title>
          <Text
            c="gray"
            style={{
              fontSize: "var(--mantine-font-size-xs)",
              textAlign: "center",
              marginTop: "5px",
            }}
          >
            Create your account and start your gamified learning journey
          </Text>
          <TextInput
            label="Full Name"
            placeholder="Enter your full name"
            required
            radius="md"
          />
          <TextInput
            ref={email}
            label="Email"
            placeholder="yourname@gmail.com"
            required
            radius="md"
          />
          <PasswordInput
            ref={password_1}
            label="Create Password"
            placeholder="Create a password"
            required
            mt="md"
            radius="md"
            value={password}
            onChange={(e) => setPassword(e.currentTarget.value)}
          />
          <PasswordInput
            ref={password_2}
            label="Confirm Password"
            placeholder="Confirm your password"
            required
            mt="md"
            radius="md"
          />
          <Group justify="space-between" mt="lg">
            <Checkbox label="I agree to the Terms and Conditions" fw={700} />
          </Group>
          <Button
            fullWidth
            mt="xl"
            radius="md"
            styles={{
              root: {
                backgroundColor: "black",
                color: "white",
                fontWeight: 500,
                "&:hover": { backgroundColor: "#222" },
              },
            }}
            onClick={handleClick}
          >
            Sign Up
          </Button>
          <br />
          <Text
            style={{
              color: "var(--mantine-color-dimmed)",
              fontSize: "var(--mantine-font-size-xs)",
              textAlign: "center",
              marginTop: "5px",
            }}
          >
            Already have an account?{" "}
            <Anchor
              styles={{
                root: {
                  color: "black",
                  fontWeight: 400,
                },
              }}
              onClick={() => navigate("/")}
            >
              Sign in
            </Anchor>
          </Text>
        </Paper>
      </Container>
    </Box>
  );
}
