import {
  Anchor,
  Box,
  Button,
  Center,
  Checkbox,
  Container,
  Group,
  Image,
  Paper,
  PasswordInput,
  Text,
  TextInput,
  Title,
} from '@mantine/core';
import { useEffect, useState } from 'react';
import { Form, useActionData, useNavigate } from 'react-router-dom';
import logo from '~/assets/logo.png';
import {
  LOGIN,
  SIGN_UP_ALREADY_HAVE_ACCOUNT_TEXT,
  SIGN_UP_BUTTON_TEXT,
  SIGN_UP_DESCRIPTION,
  SIGN_UP_HEADER,
  SIGN_UP_RULE_1,
  SIGN_UP_RULE_2,
  SIGN_UP_RULE_3,
  SIGN_UP_RULE_4,
  SIGN_UP_RULE_5,
  SIGN_UP_SIGN_IN_BUTTON_TEXT,
} from '~/constants';
import { displayNotifications } from '~/utilities/notifications/displayNotifications';
import { equalPasswords, validateEmail } from '~/utilities/validation';

export const SignUpForm = () => {
  const navigate = useNavigate();
  const actionData = useActionData();

  const [password1, setPassword1] = useState('');
  const [password2, setPassword2] = useState('');
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [_error, setError] = useState('');

  //The logic for updating the color state of the password requirement text was generated by chatGPT
  const passwordLen = 8;
  const checkRules = (value: string) => ({
    hasDigit: /\d/.test(value),
    hasLowercase: /[a-z]/.test(value),
    hasSpecial: /[@#$%^&*()\-_+=]/.test(value),
    hasUppercase: /[A-Z]/.test(value),
    matchesLen: value.length > passwordLen,
  });
  const rules = checkRules(password1);

  useEffect(() => {
    if (!actionData) return;

    // success false but message might not exist
    const message = actionData.message;

    if (typeof message === 'string' && message.includes('409')) {
      displayNotifications('Signup Error', 'Email already exists!', 'red');
    }
  }, [actionData]);

  const handleClick = async (_e: React.FormEvent) => {
    try {
      validateEmail(email) && equalPasswords(password1, password2) && name;
    } catch (err: unknown) {
      let message = 'An unknown error occurred.';

      if (err instanceof Error) {
        message = err.message;
      } else if (typeof err === 'object' && err !== null && 'message' in err) {
        message = String((err as { message?: unknown }).message);
      }

      if (message.includes('User already registered')) {
        displayNotifications(
          'Error',
          'An account with this email already exists.',
          'red',
        );
      } else {
        displayNotifications('Error', message, 'red');
      }

      setError(message);
    }
  };

  return (
    <Box
      style={{
        alignItems: 'center',
        background: 'linear-gradient(135deg, #e0f0ff 0%, #4a90e2 100%)',
        backgroundColor: '#f0f0f0',
        display: 'flex',
        justifyContent: 'center',
        margin: '0',
        minHeight: 'center',
        padding: '20px',
      }}
    >
      <Container className='classes.container' my={40} size={420}>
        <Paper mt={30} p={22} radius='lg' withBorder>
          <Text c={rules.matchesLen ? 'green' : 'red'}>{SIGN_UP_RULE_1}</Text>
          <Text c={rules.hasLowercase ? 'green' : 'red'}>{SIGN_UP_RULE_2}</Text>
          <Text c={rules.hasUppercase ? 'green' : 'red'}>{SIGN_UP_RULE_3}</Text>
          <Text c={rules.hasDigit ? 'green' : 'red'}>{SIGN_UP_RULE_4}</Text>
          <Text c={rules.hasSpecial ? 'green' : 'red'}>{SIGN_UP_RULE_5}</Text>
        </Paper>
        <Paper mt={30} p={22} radius='lg' withBorder>
          <Title ff='Inter, sans-serif' ta='center'>
            {SIGN_UP_HEADER}
          </Title>
          <Text c='dimmed' style={{ textAlign: 'center' }}>
            {SIGN_UP_DESCRIPTION}
          </Text>
          <Form method='post' onSubmit={handleClick}>
            <TextInput
              label='Full Name'
              name='name'
              onChange={(e) => setName(e.target.value)}
              placeholder='Enter your full name'
              radius='md'
              required
              variant='filled'
            />
            <TextInput
              label='Email'
              name='email'
              onChange={(e) => setEmail(e.target.value)}
              placeholder='yourname@gmail.com'
              required
              variant='filled'
            />
            <PasswordInput
              label='Create Password'
              mt='md'
              name='password'
              onChange={(e) => setPassword1(e.target.value)}
              placeholder='Create a password'
              required
              variant='filled'
            />
            <PasswordInput
              fw={600}
              label='Confirm Password'
              mt='md'
              onChange={(e) => setPassword2(e.target.value)}
              placeholder='Confirm your password'
              radius='md'
              required
              variant='filled'
            />
            <Group justify='space-between' mt='lg'>
              <Checkbox
                fw={700}
                label='I agree to the Terms and Conditions'
                required
                variant='filled'
              />
            </Group>
            <Button fullWidth mt='xl' radius='md' type='submit'>
              {SIGN_UP_BUTTON_TEXT}
            </Button>
          </Form>
          <br />
          <Text c='dimmed' style={{ textAlign: 'center' }}>
            {SIGN_UP_ALREADY_HAVE_ACCOUNT_TEXT}{' '}
            <Anchor onClick={() => navigate(LOGIN)} styles={{}}>
              {SIGN_UP_SIGN_IN_BUTTON_TEXT}
            </Anchor>
          </Text>
        </Paper>
      </Container>
    </Box>
  );
};
